# 00c-environment known after initialization of the vault

# - name: get vault address from cluster
#   kubernetes.core.k8s_info:
#     api_version: v1
#     kind: Service
#     namespace: "{{ vault.namespace }}"
#     name: "{{ vault.name }}"
#   register: vault_service

# #this part might be used inside of a container that runs ansible and basically deploys vault in the same cluster.
# - name: set vault address
#   set_fact:
#     vault:
#       address: "http://{{ vault.name }}.{{ vault.namespace }}.svc.cluster.local:8200"

# TODO
- name: construct environment variables
  set_facts:
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
      VAULT_ADDR: "{{ hostvars[inventory_hostname].vault.address }}"
      VAULT_TOKEN: "{{ lookup('vars', 'initVault')['cluster_keys.json'].destination.replace('~', ansible_env.HOME) }}"

- name: load cluster_keys.json var from file
    include_vars:
      file: "{{ lookup('vars','cluster_keys.json').destination.replace('~', ansible_env.HOME) }}"
      name: cluster_keys

- name: set facts from cluster-keys.json
  set_fact:
    unseal_keys_b64: "{{ cluster_keys.unseal_keys_b64 }}"
    root_token: "{{ cluster_keys.root_token }}"