# 00c-environment known after initialization of the vault

- name: load cluster_keys.json var from file for unsealing and configuration
  include_vars:
    file: "{{ lookup('vars','unsealVault')['cluster_keys.json'].replace('~', ansible_env.HOME) }}"
    name: cluster_keys


# load keycloak client credentials in order to configure the JWT, OIDC authentification workflows
- name: load keycloak credentials var from file
  include_vars:
    file: secrets/keycloak.yaml
    name: keycloak


- name: construct environment variables, keycloak urls and get unseal keys & root token
  set_facts:
    unseal_keys_b64: "{{ cluster_keys.unseal_keys_b64.join(' ') }}"
    root_token: "{{ cluster_keys.root_token }}"

    discovery_url: "{{ keycloak.url.rstrip('/') }}/auth/realms/{{ keycloak.realm }}"
    jwks_url: "{{ keycloak.url.rstrip('/') }}/auth/realms/{{ keycloak.realm }}/protocol/openid-connect/certs"

    environment:
      KUBECONFIG: "{{ kubeconfig }}"
      VAULT_ADDR: "{{ vault.address }}"
      VAULT_TOKEN: "{{ cluster_keys.initVault'['cluster_keys.json'].replace('~', ansible_env.HOME) }}"