- name: enable JWT auth
  hashivault_auth_method:
    method_type: jwt
  environment: "{{ environment }}"

- name: configure Keycloak JWT
  hashivault_oidc_auth_method_config:
    mount_point: jwt
    default_role: reader
    bound_issuer: "{{ discovery_url }}"
    jwks_url: "{{ jwks_url }}"
  environment: "{{ environment }}"

- name: "create {{ item }} JWT role"
  hashivault_oidc_auth_role:
    name: "{{ item }}"
    mount_point: jwt
    # actual payload values below
    user_claim: sub
    bound_audiences:
      - "{{ keycloak.client_id }}"
    token_policies:
      - "{{ item }}"
    token_ttl: 3600
    groups_claim: "/resource_access/{{ keycloak.client_id }}/roles"
    bound_claims: "{{ lookup('template', 'payload/bound_claims.yaml') | from_yaml }}"
    # workaround: only needed by the ansible vault plugin, not actually needed by vault.
    # https://github.com/TerryHowe/ansible-modules-hashivault/issues/336
    allowed_redirect_uris: ""
  environment: "{{ environment }}"
  with_items: "{{ policies.names }}"

- name: create external JWT groups
  hashivault_identity_group:
    name: "external_jwt_{{ item }}"
    group_type: "external"
    metadata:
      responsibility: "{{ item }} of k/v secrets"
  environment: "{{ environment }}"
  with_items: "{{ policies.names }}"
  register: external_jwt_groups

- name: "get JWT auth list"
  hashivault_auth_list:
  register: auth_list
  environment: "{{ environment }}"

- name: create JWT external group aliases
  hashivault_identity_group_alias:
    name: "{{ item.0 }}"
    mount_accessor: "{{ auth_list.backends['jwt/'].accessor }}"
    group_name: "{{ item.1.data.name }}"
  environment: "{{ environment }}"
  with_together:
    - "{{ policies.names }}"
    - "{{ external_jwt_groups.results }}"
  register: jwt_groups
  when: external_jwt_groups.changed