- name: stage 08 - configure secrets
  hosts: localhost
  gather_facts: true
  tasks:

  - name: is stage enabled
    set_fact:
      configureSecretsEnabled: "{{ lookup('vars', 'configureSecrets').enabled | default(True) }}"

  - name: load cluster_keys.json var from file for ssh
    include_vars:
      file: "{{ lookup('vars','cluster_keys').replace('~', ansible_env.HOME) }}"
      name: cluster_keys
    when: configureSecretsEnabled and (cluster_keys.root_token is undefined)

  - name: get environment & variables
    set_fact:
      remote_env:
        KUBECONFIG: "{{ lookup('vars', 'kubeconfig').replace('~', ansible_env.HOME) }}"
        VAULT_ADDR: "{{ lookup('vars', 'vault').address | default('http://' + vault.name + '.' + vault.namespace + '.svc.cluster.local:8200') }}"
        VAULT_TOKEN: "{{ cluster_keys.root_token }}"
    when: configureSecretsEnabled

  - name: enable secrets engine generic
    hashivault_secret_engine:
      name: secrets
      backend: kv
    environment: "{{ remote_env }}"
    when: configureSecretsEnabled

  - name: write example secret
    hashivault_secret:
      mount_point: "secrets/example/"
      secret: example-secret
      data:
        foo: foe
        fie: fum
    environment: "{{ remote_env }}"
    when: configureSecretsEnabled
