- name: enable secrets engine generic
  hashivault_secret_engine:
    name: secrets
    backend: kv
  environment: "{{ ewnvironment }}"
  register: secrets_engine

- name: write example secret
  hashivault_secret:
    mount_point: "secrets/example/"
    secret: example-secret
    data:
      foo: foe
      fie: fum
  environment: "{{ ewnvironment }}"
