- name: stage 10 - configure SSH
  hosts: localhost
  gather_facts: false
  tasks:

  - name: is stage enabled
    set_fact:
      configureSSHEnabled: "{{ lookup('vars', 'configureSSH').enabled | default(True) }}"

  - name: get environment & variables
    set_fact:
      privateKeyLocation: "{{ lookup('vars', 'configureSSH').privateKeyLocation.replace('~', ansible_env.HOME) | default('secrets/ssh')}}"
      publicKeyLocation: "{{ lookup('vars', 'configureSSH').publicKeyLocation.replace('~', ansible_env.HOME) | default('secrets/ssh.pub')}}"
      remote_env:
        KUBECONFIG: "{{ lookup('vars', 'kubeconfig').replace('~', ansible_env.HOME) }}"
        VAULT_ADDR: "{{ lookup('vars', 'vault').address | default('http://' + vault.name + '.' + vault.namespace + '.svc.cluster.local:8200') }}"
        VAULT_TOKEN: "{{ cluster_keys.root_token }}"
    when: configureSSHEnabled

  - name: read public & private keys
    set_fact:
      privateKey: "{{ lookup('file', privateKeyLocation) }}"
      publicKey: "{{ lookup('file', publicKeyLocation) }}"

  - name: enable SSH secrets engine
    hashivault_secret_engine:
      name: ssh
      backend: ssh
    environment: "{{ remote_env }}"
    register: ssh_engine
    when: configureSSHEnabled

# todo first read before or allow failure of this task
  - name: import private & public key
    hashivault_write:
      mount_point: ssh
      secret: config/ca
      data:
        private_key: "{{ privateKey }}"
        public_key: "{{ publicKey }}"
    environment: "{{ remote_env }}"
    when: configureSSHEnabled