# 01-deploy-vault
- name: stage 01 - deploy vault
  hosts: all
  gather_facts: true
  tasks:
  - name: is stage enabled
    set_fact:
      deployVaultEnabled: "{{ lookup('vars', 'deployVault').enabled | default(False) }}"

  - name: get environment & variables
    set_fact:
      kubeconfig: "{{ lookup('vars', 'kubeconfig').replace('~', ansible_env.HOME) }}"
      vault: "{{ lookup('vars', 'vault') }}"
      vaultValuesLocation: "{{ lookup('vars', 'deployVault').vaultValuesLocation | default('values/vault-values.yaml') }}"
      consulValuesLocation: "{{ lookup('vars', 'deployVault').consulValuesLocation | default('values/consul-vault-values.yaml') }}"
    when: deployVaultEnabled


  - name: helm diff plugin
    kubernetes.core.helm_plugin:
      state: present
      plugin_path: https://github.com/databus23/helm-diff
    when: deployVaultEnabled

  - name: add helm chart repos
    kubernetes.core.helm_repository:
      state: present
      name: hashicorp
      repo_url: https://helm.releases.hashicorp.com
    when: deployVaultEnabled

  - name: deploy vault
    kubernetes.core.helm:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      release_name: "{{ vault.name }}"
      release_namespace: "{{ vault.namespace }}"
      create_namespace: "{{ vault.create_namespace }}"
      chart_ref: hashicorp/vault
      release_values: "{{ lookup('template', vaultValuesLocation) | from_yaml }}"
    when: deployVaultEnabled

  - name: deploy consul
    kubernetes.core.helm:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      release_name: "{{ vault.name }}-db"
      release_namespace: "{{ vault.namespace }}"
      create_namespace: "{{ vault.create_namespace }}"
      chart_ref: hashicorp/consul
      release_values: "{{ lookup('template', consulValuesLocation) | from_yaml }}"
      wait: yes
    when: deployVaultEnabled