
# this stage is not possible to execute unless you put stages 5 through 7 in a single file.
# from my tetsing it seem sthat internal groups are not necessarily needed in order to enforce mapping of client id role
# to vault groups which have the corresponding acl policies attached to them.
- name: stage 07 - create internal groups
  hosts: all
  gather_facts: true
  tasks:

  - name: load cluster_keys.json var from file for ssh
    include_vars:
      file: "{{ lookup('vars','cluster_keys').replace('~', ansible_env.HOME) }}"
      name: cluster_keys
    when: (configureJWTEnabled or configureOIDCEnabled) and (cluster_keys.root_token is undefined)

  - name: load keycloak credentials var from file
    include_vars:
      file: "{{ lookup('vars', 'keycloakCredentials') }}"
      name: keycloak
    when: configureJWTEnabled or configureOIDCEnabled

  - name: get environment & variables
    set_fact:
      kubeconfig: "{{ lookup('vars', 'kubeconfig').replace('~', ansible_env.HOME) }}"
      vault: "{{ lookup('vars', 'vault') }}"
      policiesDir: "{{ lookup('vars', 'policiesDir').strip('/').replace('~', ansible_env.HOME) | default('policies') }}"

      remote_env:
        KUBECONFIG: "{{ lookup('vars', 'kubeconfig').replace('~', ansible_env.HOME) }}"
        VAULT_ADDR: "{{ lookup('vars', 'vault').address | default('http://127.0.0.1:8200') }}"
        VAULT_TOKEN: "{{ cluster_keys.root_token }}"
    when: configureJWTEnabled or configureOIDCEnabled

  - name: get policy files and names
    set_fact:
      policies:
        names: "{{ lookup('fileglob', policiesDir + '/*.hcl').split(',') | map('basename') | map('splitext') | map('first') | list }}"
    when: configureJWTEnabled or configureOIDCEnabled


  - name: create internal groups
    hashivault_identity_group:
      name: "{{ item }}"
      group_type: "internal"
      policies:
        - "{{ item }}"
      metadata:
        responsibility: "{{ item.0 }} of k/v secrets"
    environment: "{{ remote_env }}"
    with_items: "{{ policies.names }}"
    register: internal_groups
    when: configureJWTEnabled or configureOIDCEnabled
